version: '3'
services:
  drone-server:
    container_name: 'drone-server'
    image: drone/drone:0.8.9
    ports:
      - 18000:8000
      - 9000:9000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_URL=${DRONE_GITHUB_URL}
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_GITHUB_PRIVATE_MODE=true
    network_mode: 'imageup'
    restart: always

  drone-agent:
    container_name: 'drone-agent'
    image: drone/agent:0.8.9
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
    network_mode: 'imageup'
    restart: always
