version: '3'
services:
  mysql:
    container_name: 'mysql'
    image: mysql:8
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: develop
    volumes:
      - imageup:/var/lib/mysql
    network_mode: 'imageup'
    restart: always

volumes:
  imageup:
