version: '3'
services:
  minio:
    container_name: 'minio'
    image: minio/minio:latest
    command: server /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=develop_key
      - MINIO_SECRET_KEY=develop_key
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    network_mode: 'imageup'
    restart: always
