# Generated by Django 2.1.4 on 2019-01-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageup', '0002_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='GetPostImage',
        ),
    ]
