runserver:
	docker-compose -f ../gunicorn/docker-compose.yml up -d

stopserver:
	docker-compose -f ../gunicorn/docker-compose.yml stop

down:
	docker-compose -f ../gunicorn/docker-compose.yml down

ps:
	docker-compose -f ../gunicorn/docker-compose.yml ps
